### ISSUE TITLE
How to foreach over an array of new files

### ISSUE THREAD

**Issue by wendellm** [mariusGundersen/gulp-forEach#10]
I have a question, is there a way if I had like an array name and string content for files like this: http://stackoverflow.com/questions/33054670/how-to-create-multiple-files-in-one-gulp-task

i've tried but i cant seem to get foreach to loop is this just not possible or am I missing something? 

thanks any help would be welcome?

**Comment by mariusGundersen** [comment]
You can create a [vinyl file](https://www.npmjs.com/package/vinyl) using a constructor. If you want to create many, use [].map():

```
var files = [{path: "src/js/file1.js",contents: "some js content"},
             {path: "src/file2.html",contents: "some html content"},
             {path: "src/css/file3.css",contents: "some css content"}];
var vinylFiles = files.map(file => new File(file));
```
