### ISSUE TITLE
Feature request: filter out files

### ISSUE THREAD

**Issue by duzun** [mariusGundersen/gulp-forEach#12]
It would be nice to be able to filter out some files.

Eg. exclude `*.min.js` files from task: 

```js
// ...
.pipe(foreach(function(stream, file){
    if ( path.extname(path.basename(file.name, '.js')) == '.min' ) return false;
    return stream.pipe(uglify());
})
```

**Comment by mariusGundersen** [comment]
There are several other gulp plugins for doing that, for example [gulp-filter](https://www.npmjs.com/package/gulp-filter)

**Comment by duzun** [comment]
True, but it still would be nice to avoid using an extra plugin for such a simple task at this point.

**Comment by mariusGundersen** [comment]
The gulp philosophy is to have many simple plugins that all do one thing well instead of having many complex plugins that overlap in functionality and features.
