### ISSUE TITLE
File.name won't work.

### ISSUE THREAD

**Issue by AntiMoron** [mariusGundersen/gulp-forEach#4]
The sample code seems not working.

```javascript
gulp.src(['watch/screens/**/*tpl.html'])
  .pipe(foreach(function(stream,file){
    gutil.log(file.name);
}
```

output is a column of ```undefined```
How can I get the path of a certain File object imported  with ```gulp.src```

**Comment by AntiMoron** [comment]
Buy the way,I'm using ```gulp-util``` for logging.

```javascript
var gutil = require('gulp-util')
```

**Comment by AntiMoron** [comment]
Alright then. I found that ```file.path``` is the path of a File object of nodeJs accidentally. Tks anyway.

**Comment by mariusGundersen** [comment]
That's not good! It should probably be basename, not name. I'll update the documentation! Thank you for the feedback.

**Comment by AntiMoron** [comment]
It's my pleasure helping you make it better. :)

**Comment by AntiMoron** [comment]
```file.base``` for absolute direction of file.
```file.path``` for absolute path of file

**Comment by iBaryo** [comment]
hmm now file.base is the directory, and file.history is the directory+file name..
file.name return undefined -  where is it available?

**Comment by mariusGundersen** [comment]
`file` is a [vinyl](https://github.com/wearefractal/vinyl) object, so you have access to the properties of this object. It doesn't provide just the name of the file, but you can combine it with `path` to get it:

```js
var path = require('path');
var foreach = require('gulp-foreach');

gulp.src('*.js')
.pipe(foreach(function(stream, file){
  var name = path.filename(file.path);
});

```

**Comment by iBaryo** [comment]
thanks!

**Comment by gigadie** [comment]
it's actually
    var path = require('path');
    var foreach = require('gulp-foreach');

    gulp.src('*.js')
        .pipe(foreach(function(stream, file){
            var name_wo_ext = path.basename(file.path, '.js'); //if you want the name without extension
            var name_w_ext = path.basename(file.path, '.js'); //if you want the name with extension
        });

**Comment by brian-lamb-software-engineer** [comment]
@gigadie did you mean 
```var name_wo_ext = path.basename(file.path); ```?

**Comment by gigadie** [comment]
yes you are right, the 2 options should have been:
```javascript
var name_wo_ext = path.basename(file.path, '.js'); //if you want the name without extension
var name_w_ext = path.basename(file.path); //if you want the name with extension
```
