### ISSUE TITLE
"(node) warning: possible EventEmitter memory leak detected" when try to modify a stream

### ISSUE THREAD

**Issue by dudesl** [mariusGundersen/gulp-forEach#9]
I use gulp-foreach to modify the name of asset names in a set of css sheets by this way:

```
.pipe($.foreach(function(stream, file){
            var fileName = path.basename(file.path, '.css');

            var assetsManifest = JSON.parse(fs.readFileSync(dest.dist.manifest + "images-manifest.json", 'utf-8'));
            
            _.each(assetsManifest, function (n, key) {
                  // this line produce the memory leak warning
                  stream.pipe($.replace(key, n))
            })

            return stream
                .pipe($.minifyCss())
                .pipe($.size({
                    title: fileName + '.min.css size: '
                }))
                .pipe(gulp.dest(dest.dist.styles))
                .pipe($.gzip())
                .pipe($.size({
                    title: fileName + '.min.css.gz size: '
                }))
                .pipe(gulp.dest(dest.dist.styles));
        }))
```
This is the console log:
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Readable.EventEmitter.addListener (events.js:160:15)
    at Readable.on (_stream_readable.js:689:33)
    at Readable.EventEmitter.once (events.js:185:8)
    at Readable.pipe (_stream_readable.js:474:9)
    at /home/.../gulpfile.js:283:23
``` 

[There's a lot of npm modules whit this issue](https://www.google.com.ar/search?q=(node)+warning%3A+possible+EventEmitter+memory+leak+detected.+11+listeners+added.+Use+emitter.setMaxListeners()+to+increase+limit.&oq=(node)+warning%3A+possible+EventEmitter+memory+leak+detected.+11+listeners+added.+Use+emitter.setMaxListeners()+to+increase+limit.&aqs=chrome..69i57.330j0j7&sourceid=chrome&es_sm=93&ie=UTF-8#q=(node)+warning:+possible+EventEmitter+memory+leak+detected.+in-url:github). This is probably a node.js bug.
More info 
[http://stackoverflow.com/a/16222062](http://stackoverflow.com/a/16222062)
[https://github.com/nodejs/node-v0.x-archive/issues/5108](https://github.com/nodejs/node-v0.x-archive/issues/5108)

If you have a workaround let us know. When I have some time, I will try to fix it and make a PR.

Greetings!

**Comment by mariusGundersen** [comment]
What is `$.replace`, and why are you piping into it without using the result? It looks like you are mutating the contents of the file objects in place, which is not a good idea (always assume that the stuff you are sending down the stream is immutable and being copied from one `pipe` to the next).

Instead of foreaching outside the `stream.pipe`, why not try to foreach inside the `pipe(...)`? That way you don't fork the stream multiple times. You could use [`gulp-map`](https://www.npmjs.com/package/gulp-map) for that. For example:

```js
.pipe($.foreach(function(stream, file){
    var fileName = path.basename(file.path, '.css');

    var assetsManifest = JSON.parse(fs.readFileSync(dest.dist.manifest + "images-manifest.json", 'utf-8'));

    return stream
        .pipe(map(function(file){
            _.each(assetManifest, function(n, key){
                file.contents.replace(key, n);
                return file;
            });
        }))
        .pipe($.minifyCss())
        .pipe($.size({
            title: fileName + '.min.css size: '
        }))
        .pipe(gulp.dest(dest.dist.styles))
        .pipe($.gzip())
        .pipe($.size({
            title: fileName + '.min.css.gz size: '
        }))
        .pipe(gulp.dest(dest.dist.styles));
}))
```
